# Generated by Django 5.1.6 on 2025-03-05 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='idea', to='posts.post'),
        ),
        migrations.AlterField(
            model_name='normal',
            name='post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='normal', to='posts.post'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sample', to='posts.post'),
        ),
    ]
