# Generated by Django 5.1.6 on 2025-03-06 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_idea_post_alter_normal_post_alter_sample_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
