# Generated by Django 5.1.6 on 2025-03-05 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social',
            name='social_name',
            field=models.CharField(choices=[('Facebook', 'Facebook'), ('Twitter', 'Twitter'), ('Instagram', 'Instagram'), ('Youtube', 'Youtube'), ('TikTok', 'TikTok'), ('spotify', 'Spotify'), ('Other', 'Other')], max_length=50),
        ),
    ]
